//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroBreweryLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicroBreweryDBEntities : DbContext
    {
        public MicroBreweryDBEntities()
            : base("name=MicroBreweryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BeerRating> BeerRatings { get; set; }
        public DbSet<Beer> Beers { get; set; }
        public DbSet<Beertype> Beertypes { get; set; }
        public DbSet<MicroBreweryRating> MicroBreweryRatings { get; set; }
        public DbSet<MicroBrewery> MicroBrewerys { get; set; }
    }
}
